/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  // export interface GlobalComponents {
  //   Avatar: typeof import('primevue/avatar')['default']
  //   Badge: typeof import('primevue/badge')['default']
  //   Column: typeof import('primevue/column')['default']
  //   DataTable: typeof import('primevue/datatable')['default']
  //   InputText: typeof import('primevue/inputtext')['default']
  //   Menubar: typeof import('primevue/menubar')['default']
  //   RouterLink: typeof import('vue-router')['RouterLink']
  //   RouterView: typeof import('vue-router')['RouterView']
  // }
  // export interface ComponentCustomProperties {
  //   Ripple: typeof import('primevue/ripple')['default']
  // }
}
